export interface FilmeInterface {
    id: number,
    titulo: string,
    descricao: string,
    classificacao: string,
    genero: string,
    duracao: number,
    dataEstreia: Date,
    setId(id: number): void,
    getId(): number,
    setTitulo(titulo: string): void,
    setDescricao(descricao: string): void,
    setClassificacao(classificacao: string): void,
    setGenero(genero: string): void,
    setDuracao(duracao: number): void,
    setDataEstreia(dataEstreia: Date): void
    getTitulo(): string,
    getDescricao(): string,
    getClassificacao(): string,
    getGenero(): string,
    getDuracao(): number,
    getDataEstreia(): Date,
}